---
- name: Add Elasticsearch apt key.
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Add logstash-forwarder repository.
  apt_repository:
    repo: 'deb http://packages.elasticsearch.org/logstashforwarder/debian stable main'
    state: present

- name: Check if logstash-forwarder is already installed.
  stat: path=/etc/init.d/logstash-forwarder
  register: logstash_forwarder_installed

- name: Update apt cache if repository just added.
  apt: update_cache=yes
  when: logstash_forwarder_installed.stat.exists == false

- name: Install logstash-forwarder.
  apt: pkg=logstash-forwarder state=present

- name: Install logstash-forwarder init script.
  get_url:
    url: https://raw.github.com/elasticsearch/logstash-forwarder/master/logstash-forwarder.init
    dest: /etc/init.d/logstash-forwarder
    force: yes
    mode: 655

- name: Create logstash-forwarder configuration file.
  template:
    src: logstash-forwarder.j2
    dest: /etc/logstash-forwarder
    mode: 644
  notify: restart logstash-forwarder

- name: Ensure Logstash SSL key pair directory exists.
  file:
    path: "{{ logstash_ssl_dir }}"
    state: directory

- name: Copy SSL key and cert for logstash-forwarder.
  copy:
    src: "{{ logstash_forwarder_ssl_certificate_file }}"
    dest: "{{ logstash_ssl_dir }}/{{ logstash_forwarder_ssl_certificate_file }}"
    mode: 644
  notify: restart logstash-forwarder

- name: Ensure logstash-forwarder is started and enabled on boot.
  service: name=logstash-forwarder state=started enabled=yes
